/**
 * Catálogo fijo de permisos (recurso.acción). Es la única fuente de verdad:
 * los roles personalizados solo pueden seleccionar permisos de esta lista
 * (regla "los permisos solo existen en el catálogo en código").
 */
export const PERMISSIONS = [
  'users.read',
  'users.create',
  'users.update',
  'users.delete',
  'users.invite',
  'roles.read',
  'roles.create',
  'roles.update',
  'roles.delete',
  'stores.read',
  'stores.create',
  'stores.update',
  'stores.delete',
  'settings.read',
  'settings.update',
  'activity-log.read',
  'regions.read',
  'regions.create',
  'regions.update',
  'regions.delete',
  'territories.read',
  'territories.create',
  'territories.update',
  'territories.delete',
  'zones.read',
  'zones.create',
  'zones.update',
  'zones.delete',
  'brands.read',
  'brands.create',
  'brands.update',
  'brands.delete',
  'products.read',
  'products.create',
  'products.update',
  'products.delete',
  'categories.read',
  'categories.create',
  'categories.update',
  'categories.delete',
  'collections.read',
  'collections.create',
  'collections.update',
  'collections.delete',
  'product-types.read',
  'product-types.create',
  'product-types.update',
  'product-types.delete',
  'product-tags.read',
  'product-tags.create',
  'product-tags.update',
  'product-tags.delete',
  'sales-channels.read',
  'sales-channels.create',
  'sales-channels.update',
  'sales-channels.delete',
  'inventory.read',
  'inventory.update',
  'media.read',
  'media.create',
  'media.delete',
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export function isPermission(value: string): value is Permission {
  return (PERMISSIONS as readonly string[]).includes(value);
}
